# Porta da Aplicacao REST
server.port=8080

# Nome da Aplicacao
spring.application.name=baozi-store

# Configuracao do Banco de Dados Relacional H2 (Em Memoria)
spring.datasource.url=jdbc:h2:mem:baozidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o Console Web do H2 para testes e demonstracao
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracoes de JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
